sealed abstract class Region(val name: String)
object Region {
  case object BR1 extends Region("br1")
  case object EUN1 extends Region("eun1")
  case object EUW1 extends Region("euw1")
  case object JP1 extends Region("jp1")
  case object KR extends Region("kr")
  case object LA1 extends Region("la1")
  case object LA2 extends Region("la2")
  case object NA1 extends Region("na1")
  case object OC1 extends Region("oc1")
  case object TR1 extends Region("tr1")
  case object RU extends Region("ru")
  case object PH2 extends Region("ph2")
  case object SG2 extends Region("sg2")
  case object TH2 extends Region("th2")
  case object TW2 extends Region("tw2")
  case object VN2 extends Region("vn2")
}
